name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    uses: ukasyah-dev/actions/.github/workflows/build-docker-sveltekit.yaml@main
    permissions:
      contents: read
      packages: write
    secrets: inherit
  
  deploy:
    uses: ukasyah-dev/actions/.github/workflows/deploy-docker.yaml@main
    needs: build
    permissions:
      contents: read
    secrets: inherit
